name: continuous

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Android Linter
      run: ./gradlew lintDebug
    - name: Run Detekt Linter
      run: ./gradlew detektAll
      if: ${{ always() }}
    - name: Build Debug AAR with Gradle
      run: ./gradlew assembleDebug
    - name: Upload AAR
      uses: actions/upload-artifact@v2
      with:
        name: Library
        path: ${{ github.workspace }}/lib/build/outputs/aar/lib-debug.aar
