name: continuous

on: [push, pull_request]

jobs:
  validate:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1

  build:
    name: Build, lint and run tests
    runs-on: ubuntu-latest
    needs: validate

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run Detekt Linter
      run: ./gradlew detekt
      if: success() || failure()

    - name: Run Android Linter
      run: ./gradlew lint
      if: success() || failure()

    - name: Build Debug AAR with Gradle
      run: ./gradlew assembleDebug
      if: success() || failure()

    - name: Upload AAR
      uses: actions/upload-artifact@v3
      with:
        name: Library
        path: ${{ github.workspace }}/lib/build/outputs/aar/lib-debug.aar
