name: continuous

on: [push, pull_request]

jobs:
  validate:
    uses: ./.github/workflows/validate-gradlew.yml

  lint:
    uses: ./.github/workflows/lint.yml
    needs: validate

  detekt:
    uses: ./.github/workflows/lint-detekt.yml
    needs: validate

  build:
    uses: ./.github/workflows/assembleDebug.yml
    needs: validate
    with:
      assembly_path: lib/build/outputs/aar/lib-debug.aar
